# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/SinzyYin"

    [social.params]
       icon = "brand-github"

[[social]]
    identifier = "linkedin"
    name = "Linkedin"
    url = "https://www.linkedin.com/in/yapsinyin/"

    [social.params]
        icon = "brand-linkedin"

[[social]]
    identifier = "resume"
    name = "Resume"
    url = "https://drive.google.com/file/d/1KZ2ARXw8H58uVYxW_q8JsKNu5LYS9MMe/view?usp=sharing"

    [social.params]
     icon = "file-cv"
