title: Sin Yin # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Final Year Communication Student at INTI International College Subang | Major in Advertising & Social Media | Minor in Digital Marketing
  <br><br>
  Second description 
  <br><br>
  <img 
    src="https://img.icons8.com/?size=100&id=8808&format=png&color=000000" 
    alt="LinkedIn Logo" 
    style="height:14px; margin-left:3px; vertical-align:text-bottom;"
  />  
    <a href="https://www.linkedin.com/in/yapsinyin/">
      View My LinkedIn Profile
   </a>
  <br><br>
  <img 
    src="https://img.icons8.com/?size=100&id=12599&format=png&color=000000" 
    alt="GitHub Logo" 
    style="height:14px; margin-left:3px; vertical-align:text-bottom;"
  />
   <a href="https://github.com/SinzyYin">
      View My GitHub Profile
   </a>
  <br><br>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-K80XWS7126 # your Google Analytics tracking ID here
